app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'

urlpatterns=[
    path('sourav/',sourav,name='sourav'),
    path('Asish/',Asish,name='Asish'),
]

project8/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import *
import app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('Registration/',Registration,name="Registration"),
    path('online_Form/',online_Form,name="online_Form"),
    path('app2/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.

def Registration(request):
    return render(request,'h1.html')

def online_Form(request):
    return render(request,'h2.html')    

app2/views.py
from django.shortcuts import render

# Create your views here.
def sourav(request):
    return render(request,'sourav.html')

def Asish(request):
    return render(request,'Asish.html')    

templates/Asish.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>CSS ROTATE</title>
	<style>
	    body
	    {
	    	background-image: url(https://image.freepik.com/free-photo/close-up-image-programer-working-his-desk-office_1098-18707.jpg);
	    }
		div
		{
			width: 350px;
			height: 200px;
			box-shadow: 0 0 10px black;
			margin: 60px auto;
			border-radius: 30px;
			overflow: hidden;
			position: relative;
		}
		div img
		{
			width: inherit;
			height: inherit;
			border-radius: inherit;
			transition: all 1s linear 0s;
		}
		div:hover img
		{
			transform: translateX(50%);
			border-radius: 0px 30px 30px 0px;
		}
		#text
		{
			position: absolute;
			top: -60px;
			left: 0px;
			width: 50%;
			border-radius: 30px 0px 0px 30px;
			background-color: rgb(90,9,9);
			transform: perspective(200px) rotateY(90deg);
			transition: all 1s linear 0s;
			transform-origin: left;
		}
		div:hover #text
		{
			transform: perspective(200px) rotateY(0deg);
		}
	</style>
</head>
<body>
    <div>
        <img src="https://soliloquywp.com/wp-content/uploads/2019/04/nb_esc_cover.jpg">
    <div id="text">
    <p>When somebody begins a sentence with “IT WOULD BE NICE IF..” the right thing to do is to wait politely for the speaker to finish. No project ever gets around to the it-would-be-nice features: or if they do, they regret it. Wait for sentences that begin “WE HAVE TO..” and pay close attention, and see if you agree.</p>
    </div>
    </div>
    <h6><a href="{% url 'Registration' %}">Registartion page</a></h6>
    <h6><a href="{% url 'online_Form' %}">online_Form page</a></h6>
    <h6><a href="{% url 'app2:sourav' %}">sourav Page</a></h6> 	
</body>
</html>

templates/h1.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Registartion From </title>
	<style>
		body
		{
			background: white url("https://img.freepik.com/free-psd/top-view-photographer-wooden-workspace-with-laptop_23-2149021358.jpg?size=626&ext=jpg&ga=GA1.2.1347674479.1627862400"); norepeat center scroll;
			background-size: cover;
		}
		#register
		{
			background: linear-gradient(45deg,orange,blue,green);
			width: 300px;
			text-align: center;
			margin: 100px auto;
			border-radius: 20px;
			box-shadow: 0 0 10px blue;
		}
		input[type="text"],
		input[type="email"],
		input[type="password"],
		{
			margin: 15px;
			border: none;
			outline: none;
			height: 20px;
			width: 230px;
			background: transparent;
			border-bottom: 2px solid white;
			color: white;
		}
		: :placeholder
		{
			color: white;
			text-align: center;
		}
		input[type="submit"]
		{
			background: linear-gradient(45deg,violet,blue,darkred);
			color: white;
			width: 220px;
			border: none;
			outline: none;
			margin: 20px;
			padding: 7px 25px;
			border-radius: 20px;
		}
		input[type="submit"]:hover
		{
			cursor: pointer;
			box-shadow: 0 0 10px white;
		}
		#logo
		{
			width: 70px;
			height: 70px;
			margin-left: 33%;
		}
		#logo img
		{
			width: inherit;
			height: inherit;
			margin-top:-40px;
			border-radius:50%;
			border: 16px solid white;
		}
	</style>
</head>
<body>
    <div id='register'>
    	<div id='logo'>
    		<img src="https://www.groovypost.com/wp-content/uploads/2019/04/laptop-keyboard-featured-1000x450.jpg">
        </div>
        <div class="form-group">
        <input type="text" name="usn" placeholder="Enter Username">
    </div>
    <div class="form-group">
    	<input type="email" name="email" placeholder="Enter Email">
    </div>
    <div class="form-group">
    <input type="password" name="pw" placeholder="Enter password">
    </div>
    <div class="form-group">
    <input type="password" name="cpw" placeholder="Enter password">
    </div>
    <div class="form-group">
    <input type="submit" value="Registartion">
    </div>
    </div>
    <h6><a href="{% url 'online_Form' %}">Travel to online_Form page</a></h6>
    <h6><a href="{% url 'Registration' %}">Travel to Registration page</a></h6>
    <h6><a href="{% url 'app2:sourav' %}">sourav Page</a></h6> 
    <h6><a href="{% url 'app2:Asish' %}">Asish Page</a></h6> 
</body>
</html>     	
</body>
</html>

templates/h2.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Resume</title>
	<link rel="stylesheet" href="css/style01.css">

</head>

<body>
		<h1>Online Job Appication Form</h1>  
		<div>
		<form>
			<fieldset>
				<legend>Student Information</legend>
				<table>
					<tr>
						<td>FirstName</td>
						<td><input type="text" name="n1"></td>
						<td>MiddileName</td>
						<td><input type="text" name="n1"></td>
						<td>LastName</td> 
						<td><input type="text" name="n1"></td>
					</tr>
					<tr>
						<td>Father's Name</td>
						<td><input type="text" name="n1"></td>
						<td>Mother's Name</td>
						<td><input type="text" name="n1"></td>
					</tr>
					<tr>
						<td>Current Address</td>
						<td><textarea cols="24" rows="4"></textarea></td>
						<td>Permanent Address</td>
						<td><textarea cols="24" rows="4"></textarea></td>
					</tr>
					<tr><td><label>Phone Number</label></td></tr>
					<tr>
						<td>LandLine Number</td>
						<td><input type="text" name="number"></td>
						<td>Mobile Number</td>
						<td><input type="text" name="number"></td>
					</tr>
					<tr>
						<td>Date Of Birth</td>
						<td><input type="date" name="birthday"></td>
						<td>Place Of Birth</td>
						<td><input tyoe="text" name="place"></td>
					</tr>
					<tr>
						<td>Gender</td>
						<td>
							<input type="radio" name="a">Male
							<input type="radio" name="a">Female
						</td>
					</tr>
					<tr>
						<td>Highest Qualification</td>
						<td><input type="text" name="qualification"></td>
						<td>Year Of Passing</td>
						<td><input type="month" name="year"></td>
					</tr>
					<tr>
						<td>Languages Known</td>
						<td>
							<input type="checkbox" name="language">English
						    <input type="checkbox" name="language">Hindi
						    <input type="checkbox" name="language">Tamil
						</td>
					</tr>
					<tr>
						<td>Select Your Hobbies</td>
						<td colspan=2>
							<input type="checkbox" name="Hobbies">Reading
							<input type="checkbox" name="Hobbies">Travelling
							<input type="checkbox" name="Hobbies">Cooking
						</td>
					</tr>
					<tr>
						<td>About Yourself</td>
						<td><textarea cols="24" rows="4"></textarea></td>
					</tr>
					<tr>
						<td>Nationality</td>
						<td>
						<select>
							<option>India</option>
							<option>USA</option>
							<option>Italy</option>
							<option>England</option>
							<option>China</option>
							<option>Japan</option>
							<option>Germany</option>
							<option>Australia</option>
							<option>New Zealand</option>
							<option>Singapore</option>
						</select>
					</td>
					</tr>
					<tr>
						<td>AadhaarCard Number</td>
						<td><input type="text" name="aadhar"></td>
						<td>PanCard Number</td>
						<td><input type="text" name="pan"></td>
					</tr>
				</table>
			</fieldset>
			<fieldset>
				<legend>Educational Details</legend>
				<table>
					<tr>
						<td>S.no</td>
						<td>Qualification</td>
						<td>Institute/University</td>
						<td>Year Of Passing</td>
						<td>Marks in %</td>
					</tr>
					<tr>
						<td>1.</td>
						<td><input type="text" name="qualification"></td>
						<td><input type="text" name="Institute"></td>
						<td><input type="month"name="year"></td>
						<td><input type="text" name="mark"></td>
					</tr>
					<tr>
						<td>2.</td>
						<td><input type="text" name="qualification"></td>
						<td><input type="text" name="Institute"></td>
						<td><input type="month"name="year"></td>
						<td><input type="text" name="mark"></td>
					</tr>
					<tr>
						<td>3.</td>
						<td><input type="text" name="qualification"></td>
						<td><input type="text" name="Institute"></td>
						<td><input type="month"name="year"></td>
						<td><input type="text" name="mark"></td>
					</tr>
				</table>
			</fieldset>
			<fieldset>
				<table>
					<legend>Work Experience</legend>
					<tr>
						<td>S.no</td>
						<td>Work</td>
						<td>Company</td>
						<td>From Date</td>
						<td>To Date</td>
					</tr>
					<tr>
						<td>1.</td>
						<td><textarea cols="24" rows="4"></textarea></td>
						<td><textarea cols="24" rows="4"></textarea></td>
						<td><input type="month" name="date"></td>
						<td><input type="month" name="datee"></td>
					</tr>
					<tr>
						<td>2.</td>
						<td><textarea cols="24" rows="4"></textarea></td>
						<td><textarea cols="24" rows="4"></textarea></td>
						<td><input type="month" name="date"></td>
						<td><input type="month" name="datee"></td>
					</tr>
					<tr>
						<td>3.</td>
						<td><textarea cols="24" rows="4"></textarea></td>
						<td><textarea cols="24" rows="4"></textarea></td>
						<td><input type="month" name="date"></td>
						<td><input type="month" name="datee"></td>
					</tr>
				</table>
			</fieldset>
			<fieldset>
				<table>
					<legend>Other Details</legend>
						<tr>
							<td>Job Type</td>
							<td>
								<input type="radio" name="job">Permanent
								<input type="radio" name="job">Contract
								<input type="radio" name="job">Other
							</td>
						</tr>
						<tr>
							<td>Date Of Joining</td>
							<td><input type="date" name="date"></td>
							<td>Time Of Joining</td>
							<td><input type="date" name="date"></td>
						</tr>
						<tr>
							<td>Preffered Job Location</td>
							<td>
								<input type="radio" name="loaction">Bangalore
								<input type="radio" name="loaction">Chennai
								<input type="radio" name="loaction">Mumbai
							</td>
						</tr>
						<tr>
							<td>Willing to relocate</td>
							<td>
								<input type="radio" name="a">Yes
								<input type="radio" name="a">No
							</td>
						</tr>
						<tr>
							<td  colspan=3>I am here declaring that all the above mentioned information is true as per my knowledge.</td>
						</tr>
						<tr style="text-align: center;">
							<td colspan=2><input type="submit" name="submit"></td>
							<td><input type="reset" name="reset"></td>
						</tr>
					</table>
				</fieldset>
		</form>
	</div>
    <h6><a href="{% url 'Registration' %}">Travel to Registration page</a></h6>
    <h6><a href="{% url 'online_Form' %}">online_Form page</a></h6>
    <h6><a href="{% url 'app2:sourav' %}">sourav Page</a></h6> 
    <h6><a href="{% url 'app2:Asish' %}">Asish Page</a></h6> 
</body>
</html>

templates/sourav.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>CSS TRANSLATE</title>
	<style>
	     body
	     {
	     	background-image: url(https://media.gettyimages.com/photos/repairman-checking-voltage-with-digital-multimeter-picture-id1006169700?s=612x612);
	     	border-radius: 200px;
	     	width: 200px;
	     	align-items: center;
	     	margin: 20px auto;
	     }
		 div
		    {
		    	background-color: whitesmoke;
		    	width: 450px;
		    	align-items: center;
		    	height: 300px;
		    	margin: 50px auto;
		    	border-radius: 20px;
		    	overflow: hidden;
		    	position: relative;
            }
            div img
            {
            	align-items: center;
            	width: inherit;
            	height: inherit;
            	border-radius: 20px 20px 0px 0px;
            	transition: all 1s linear 0s;
            }
            div:hover img
            {
            	transform: translateY(-100px);
            }
            .details
            {
            	position: absolute;
            	top: -50px;
            	left: 0px;
            	background-color: rgb(139,23,24);
            	height: 100px;
            	color: white;
            	border-radius: 0px 0px 20px 20px;
            	margin-top: 350px;

            	transition: all 1s linear 0s;
            }
            div:hover .details
            {
            	transform: translateY(-100px);
            }
            div ul li
            {
            	border: 1px solid white;
            	width: 350px;
            	text-align: center;
            	list-style-type: none;
            }
	</style>
</head>
<body>
     <div align="center">
     	<img src="https://m.media-amazon.com/images/I/81SdJG3OUjL._SX450_.jpg">
     	<div class="details">
     		<ul>
     			<li>HP 15AMD Ryzen 7 15.6"(39.62cms)FHD Laptop(Ryzen 7-3700U/8GB/512GB</li>
     			<li>HP Laptop</li>
     			<li>&#8377;52990.00</li>
     	    </ul>
     	</div>
    </div>
    <h6><a href="{% url 'Registration' %}">Registartion page</a></h6>
    <h6><a href="{% url 'online_Form' %}">online_Form page</a></h6>
    <h6><a href="{% url 'app2:Asish' %}">Asish Page</a></h6>    		
</body>
</html>